### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by COM8** [UWPX/UWPX-Push-Server#3]
### TODO/DONE
- [x] TCP server, where UWPX will connect to and informs the server about it's accounts
    - [x]  Encrypt all the traffic using TLS1.2 and if possible 1.3
    - [x] Error handling
- [x] [Windows Push Notification Services (WNS)](https://docs.microsoft.com/en-us/windows/uwp/design/shell/tiles-and-notifications/windows-push-notification-services--wns--overview)
    - [x] Error handling
- [x] XMPP client
    - [x] Error handling
- [x] DB backend
    - [x] Error handling
